server:
  port: 3001
  read_timeout: 30s

scanner:
  max_redirects: 10
  request_timeout: 10s
  headers:
    User-Agent: "Fingerprinter/1.0"
    # Accept-Language: "en-US,en;q=0.9"
  concurrent_scans: 50
  # proxy: "http://127.0.0.1:8080"

browser:
  control_urls:
    - "http://chrome-1:9222"
    - "http://chrome-2:9222"
    - "http://chrome-3:9222"
  max_pages: 50       # max concurrent browser tabs across all instances
  page_timeout: 15s

detections:
  yaml_dir: "./detections/"

# redis:
#   url: "redis://localhost:6379"
#   stream: "scans"
