name: Swagger UI
category: JS Library
website: https://swagger.io/tools/swagger-ui/
checks:
  paths:
    - path: /api/docs
      status: 200
      browser: true
  body:
    - pattern: 'swagger-ui'
    - pattern: 'Swagger UI</title>'
  js:
    - expression: "versions['swaggerUI']['version']"
      version: true
